# **Desafío: trabajando en otros contextos**

Pongamos nuevamente en práctica todo lo que aprendimos durante la clase. He puesto los 2 nuevos conjuntos de datos disponibles para descargar a continuación:

- Proyecto Desafío 1: Ventas Online - dados_vendas_clientes.json;
- Proyecto Desafío 2: Administración de Condominios - dados_locacao_imoveis.json.

**Recuerda**: Hay dos proyectos de tratamiento que se construirán durante el curso. Así que guarde su código de construcción para cada desafío para poder aplicarlo a desafíos posteriores.

**Etapa 3**

- **Proyecto Desafío 1: Ventas Online**

En el paso 2, trabajamos en la transformación de datos numéricos. Ahora podemos trabajar con valores textuales.

Debido a una inestabilidad en el sitio web de la empresa, tuvimos problemas con los nombres de los clientes durante el guardado. Esto resultó en una columna de nombres de clientes con una combinación de letras, mayúsculas y minúsculas, números y otros caracteres.

Sabiendo esto, manipula los textos de la columna ```Cliente``` para que el resultado sean los nombres de los clientes en letras minúsculas, con ausencia de caracteres especiales o números.

- **Proyecto Desafío 2: Administración de Condominios**

En el paso 2, trabajamos en transformar los datos numéricos. Ahora podemos trabajar con valores textuales.

Buscando explicar la organización de la identificación de los apartamentos, durante la creación del conjunto de datos se añadió el texto ```(blocoAP)```. Este texto informa que los nombres de los apartamentos están organizados con la letra mayúscula seguida del número del apartamento. Sin embargo, esto no aporta ninguna información a nuestros datos, por lo que resulta interesante eliminar este texto del conjunto de datos.

Con esto, manipule los textos de la columna ```apartamento``` para eliminar el texto ```(blocoAP)``` del DataFrame.


---

In [2]:
import pandas as pd
import json
import numpy as np

In [3]:
ventas_path = "dados_vendas_clientes.json"
administracion_path = "dados_locacao_imoveis.json"

ventas_json = json.load(open(ventas_path))
administracion_json = json.load(open(administracion_path))

In [4]:
ventas = pd.json_normalize(ventas_json["dados_vendas"])
ventas.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [17]:
colummnas_ventas = ventas.columns.to_list()
ventas_explode = ventas.explode(colummnas_ventas[1:]).reset_index(drop=True)
print(ventas_explode.info())
ventas_explode["Cliente"] = ventas_explode["Cliente"].str.lower().replace("[^a-z]", "", regex=True)
ventas_explode["Valor da compra"] = ventas_explode["Valor da compra"].apply(lambda x: x.replace("R$","").replace(",",".").strip())
ventas_explode["Valor da compra"] = ventas_explode["Valor da compra"].astype(np.float64)
print(ventas_explode.info())
print(ventas_explode.head())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     str
dtypes: str(3)
memory usage: 612.0 bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), str(2)
memory usage: 612.0 bytes
None
  Data de venda        Cliente  Valor da compra
0    06/06/2022       analucia           836.50
1    06/06/2022  diegoarmandiu           573.33
2    06/06/2022  diegoarmandiu           392.80
3    06/06/2022  diegoarmandiu           512.34
4    07/06/2022  isabelyjoanes           825.31

In [6]:
administracion = pd.json_normalize(administracion_json["dados_locacao"])
administracion.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

In [20]:
colummnas_administracion = administracion.columns.tolist()
administracion_explode = administracion.explode(colummnas_administracion[1:])
print(administracion_explode.info())
administracion_explode["apartamento"] = administracion_explode["apartamento"].apply(lambda x: x.replace("(blocoAP)","").strip())
administracion_explode["valor_aluguel"] = administracion_explode["valor_aluguel"].apply(lambda x: x.replace("$","").replace(",",".").replace("reais","").strip())
administracion_explode["valor_aluguel"] = administracion_explode["valor_aluguel"].astype(np.float64)
print(administracion_explode.info())
print(administracion_explode.head())

<class 'pandas.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     str
 1   datas_combinadas_pagamento  30 non-null     str
 2   datas_de_pagamento          30 non-null     str
 3   valor_aluguel               30 non-null     str
dtypes: str(4)
memory usage: 1.2 KB
None
<class 'pandas.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     str
 1   datas_combinadas_pagamento  30 non-null     str
 2   datas_de_pagamento          30 non-null     str
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), str(3)
memory usage: 1.2 KB
None
  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                 01/06/2022         05/06/2022         1000.0
0        A101                 01/07/2022         03/07/2022         2500.0
1        A102                 02/06/2022         02/06/2022         1100.0
1        A102                 02/07/2022         06/07/2022         2600.0
2        B201                 03/06/2022         07/06/2022         1200.0